import { DemoStep } from '../types/demoRecorder';

export const DEMO_PREDEFINED_DATA = {
  selectedCameraId: 'GJ-AHM-POLICE-PTZ-10571',
  selectedCameraDbId: 'cam-ahm-1',
  anprVehiclePlate: 'GJ-01-ER-4921',
  vehicleModel: 'Silver Hyundai Creta',
  movementPath: [
    { name: 'Pakwan Flyover Junction 12', id: 'GJ-AHM-POLICE-PTZ-10571', time: '14:22:10' },
    { name: 'Iskcon Crossroad Corridor', id: 'GJ-AHM-TRAFFIC-BULLET-10042', time: '14:28:45' },
    { name: 'Sanand Crossroad Checkpost', id: 'GJ-AHM-POLICE-PTZ-10118', time: '14:36:12' },
  ],
  investigationCaseId: 'case-1',
  investigationCaseNumber: 'CASE-GJ-2026-0814',
  degradedStreamId: 'stream-01',
  failoverStreamId: 'stream-02',
};

export const DEMO_STEPS: DemoStep[] = [
  {
    stepNumber: 1,
    code: 'INTRO',
    title: 'Platform Architecture & Dual-Model Overview',
    featureName: 'DRISHTI-NEXUS: Model 1 + Model 2',
    narration:
      'Welcome to DRISHTI-NEXUS: Statewide CCTV Asset Intelligence & Unified Video Analytics Platform, bridging Model 1 registry governance with Model 2 operational intelligence across Gujarat.',
    model: 'model1',
    targetTab: 'dashboard',
    targetSelector: '#platform-navbar',
    durationMs: 9000,
  },
  {
    stepNumber: 2,
    code: 'MODEL1_DASHBOARD',
    title: 'Model 1 Asset Intelligence Dashboard',
    featureName: 'KPI Cards, Coverage Debt & Telemetry Stats',
    narration:
      'Model 1 provides an authoritative master registry for over 500 state infrastructure cameras, quantifying operational uptime, coverage debt, and cross-department data conflicts in real time.',
    model: 'model1',
    targetTab: 'dashboard',
    targetSelector: '#dashboard-view',
    durationMs: 11000,
  },
  {
    stepNumber: 3,
    code: 'MODEL1_GIS',
    title: 'Geospatial Digital Twin & Camera Clusters',
    featureName: 'GIS Statewide Map & Cluster Zoom',
    narration:
      'Navigating the GIS Digital Twin across 10 Gujarat districts. Zooming directly into the high-density Ahmedabad corridor to inspect physical camera deployment and coverage footprints.',
    model: 'model1',
    targetTab: 'map',
    targetSelector: '#gis-map-view',
    durationMs: 11000,
  },
  {
    stepNumber: 4,
    code: 'DIGITAL_TWIN',
    title: 'Authoritative Digital Twin Inspection',
    featureName: 'Hardware Specs, Lifecycle, Health & Coverage',
    narration:
      'Opening the verified Digital Twin for GJ-AHM-POLICE-PTZ-10571. Reviewing cryptographic serial identity, optical azimuth, MTBF uptime score, and scheduled lifecycle replacement.',
    model: 'model1',
    targetTab: 'map',
    targetSelector: '#digital-twin-modal',
    durationMs: 13000,
  },
  {
    stepNumber: 5,
    code: 'MODEL1_DATA_INTELLIGENCE',
    title: 'Data Intelligence: Conflicts, Health & Coverage Debt',
    featureName: 'Data Quality Auditing & Gap Identification',
    narration:
      'Model 1 audits data integrity: detecting IP subnet collisions between Police and Municipal registries, flagging unmonitored arterial blind spots, and generating P1 triage tickets.',
    model: 'model1',
    targetTab: 'quality',
    targetSelector: '#data-quality-view',
    durationMs: 12000,
  },
  {
    stepNumber: 6,
    code: 'TRANSITION_TO_MODEL2',
    title: 'Seamless Continuity: Model 1 to Model 2 Transition',
    featureName: 'Global Camera ID Key Continuity',
    narration:
      'Using the authoritative key GJ-AHM-POLICE-PTZ-10571, we transition seamlessly from infrastructure registry into Model 2 live video analytics and surveillance operations.',
    model: 'model2',
    targetTab: 'video_wall',
    targetSelector: '#model-mode-switch',
    durationMs: 9000,
  },
  {
    stepNumber: 7,
    code: 'COMMAND_CENTER',
    title: 'Unified Operational Command Center',
    featureName: 'Camera & Stream Ingest Health Telemetry',
    narration:
      'The Model 2 Command Center monitors video feed availability, real-time AI alert queues, and gateway pipeline health for both synthetic and live Sentinel streams.',
    model: 'model2',
    targetTab: 'video_wall',
    targetSelector: '#video-wall-header',
    durationMs: 10000,
  },
  {
    stepNumber: 8,
    code: 'VIDEO_WALL',
    title: 'Unified Video Wall & Synchronized 2x2 Matrix',
    featureName: '2x2 Video Wall & Sub-Second PTS Clock',
    narration:
      'Activating the 2x2 multi-feed matrix. Every feed is rendered with strict 90kHz Presentation Timestamps (PTS), live bitrates, and instant PTZ camera spotlight inspection.',
    model: 'model2',
    targetTab: 'video_wall',
    targetSelector: '#video-wall-grid',
    durationMs: 12000,
  },
  {
    stepNumber: 9,
    code: 'CAPABILITY_SEARCH',
    title: 'Forensic Capability & Sensor Search',
    featureName: 'ANPR & PTZ Edge Filter Intelligence',
    narration:
      'Performing capability-based discovery across statewide assets: instantaneously locating all ANPR-enabled cameras deployed along municipal arterial corridors.',
    model: 'model2',
    targetTab: 'metadata_search',
    targetSelector: '#metadata-search-container',
    durationMs: 11000,
  },
  {
    stepNumber: 10,
    code: 'VEHICLE_SEARCH',
    title: 'Target Hotlist Vehicle Query',
    featureName: 'Statewide License Plate Lookup (GJ-01-ER-4921)',
    narration:
      'Initiating an expedited search for target vehicle GJ-01-ER-4921 (Silver Hyundai Creta), flagged under State Crime Branch stolen vehicle alert.',
    model: 'model2',
    targetTab: 'anpr',
    targetSelector: '#anpr-search-input',
    durationMs: 10000,
  },
  {
    stepNumber: 11,
    code: 'ANPR_RESULT',
    title: 'High-Confidence ANPR Detection Event',
    featureName: 'OCR Match, Vector, Speed & Confidence',
    narration:
      'ANPR hit verified at SG Highway Junction 12: 98% OCR confidence, Southbound vector at 52 km/h, linked directly to Model 1 camera metadata.',
    model: 'model2',
    targetTab: 'anpr',
    targetSelector: '#anpr-detection-card',
    durationMs: 12000,
  },
  {
    stepNumber: 12,
    code: 'MOVEMENT',
    title: 'Cross-Camera Spatial-Temporal Trajectory',
    featureName: 'Automated Journey Route: Cam A → Cam B → Cam C',
    narration:
      'Cross-Camera Movement reconstructs the target’s trajectory: Camera A at Pakwan Flyover, to Camera B at Iskcon, to Camera C at Sanand Crossroad with precise timing.',
    model: 'model2',
    targetTab: 'cross_camera',
    targetSelector: '#cross-camera-map-container',
    durationMs: 14000,
  },
  {
    stepNumber: 13,
    code: 'EVENT_TO_SOURCE',
    title: 'AI Alert-to-Source Camera Traceability',
    featureName: 'Event Feed & Source Jump',
    narration:
      'Selecting a critical AI event alert. The system instantaneously resolves the alert to its source camera, spatial coordinates, and live video buffer.',
    model: 'model2',
    targetTab: 'events',
    targetSelector: '#events-feed-list',
    durationMs: 11000,
  },
  {
    stepNumber: 14,
    code: 'EVIDENCE_CONTEXT',
    title: 'Standardized Evidence Context Inspection',
    featureName: 'Bounding Boxes, OCR Proof & Cryptographic Hash',
    narration:
      'The Evidence Context Card bundles vehicle snapshots, bounding coordinates, sensor calibration, and officer acknowledgment for tamper-proof evidentiary handling.',
    model: 'model2',
    targetTab: 'events',
    targetSelector: '#evidence-context-card',
    durationMs: 12000,
  },
  {
    stepNumber: 15,
    code: 'EVENT_CORRELATION',
    title: 'Multi-Sensor Event Clustering & Correlation',
    featureName: 'Correlated Incidents into Unified Incident',
    narration:
      'The correlation engine clusters concurrent events: pairing the ANPR detection with speed alerts and perimeter logs within a 15-minute operational window.',
    model: 'model2',
    targetTab: 'events',
    targetSelector: '#event-correlation-section',
    durationMs: 11000,
  },
  {
    stepNumber: 16,
    code: 'INVESTIGATION_WORKSPACE',
    title: 'Collaborative Investigation Dossier',
    featureName: 'Case GJ-2026-0814: Pinned Feeds, Notes & Export',
    narration:
      'Opening Investigation Case GJ-2026-0814. Reviewing pinned CCTV feeds, timeline waypoints, investigator case notes, and generating court-ready forensic reports.',
    model: 'model2',
    targetTab: 'investigations',
    targetSelector: '#investigation-dossier-view',
    durationMs: 13000,
  },
  {
    stepNumber: 17,
    code: 'STREAM_QUALITY',
    title: 'Adaptive Telemetry & Stream Quality Simulation',
    featureName: 'Telemetry Degradation: Excellent → Critical',
    narration:
      'Testing stream resilience under network degradation: transitioning from 1080p60 (4.2 Mbps) through jitter, packet loss, and low-bandwidth states with live telemetry.',
    model: 'model2',
    targetTab: 'video_wall',
    targetSelector: '#stream-telemetry-badge',
    durationMs: 11000,
  },
  {
    stepNumber: 18,
    code: 'FAILOVER',
    title: 'Feed Failure Recovery & Protocol Failover',
    featureName: 'Automatic WebRTC WHEP → HLS Fallback',
    narration:
      'Simulating feed failure: the primary WebRTC WHEP connection drops, triggers exponential backoff, and transparently fails over to secondary HLS without UI freeze.',
    model: 'model2',
    targetTab: 'video_wall',
    targetSelector: '#failover-indicator',
    durationMs: 13000,
  },
  {
    stepNumber: 19,
    code: 'SYSTEM_HEALTH',
    title: 'Automated Gateway & Pipeline Diagnostics',
    featureName: 'Ingest Tests, Mixed Codecs & TCP Enforcement',
    narration:
      'Verifying system integrity: all 5 automated compliance tests passed, certifying dynamic ingest discovery, H.264/H.265 decoding, and RTSP TCP transport.',
    model: 'model2',
    targetTab: 'live_tests',
    targetSelector: '#live-test-diagnostics',
    durationMs: 11000,
  },
  {
    stepNumber: 20,
    code: 'FINAL_UNIFIED_VIEW',
    title: 'Unified Architecture: Model 1 + Model 2 Synergy',
    featureName: 'The Complete Statewide Intelligence Lifecycle',
    narration:
      'DRISHTI-NEXUS delivers the complete operational lifecycle: from authoritative Model 1 asset lifecycle management to Model 2 real-time investigation intelligence.',
    model: 'model1',
    targetTab: 'dashboard',
    targetSelector: '#platform-navbar',
    durationMs: 10000,
  },
  {
    stepNumber: 21,
    code: 'END_CARD',
    title: 'Demo Finale & Team Apex Credits',
    featureName: 'DRISHTI-NEXUS • TEAM APEX',
    narration:
      'DRISHTI-NEXUS: From Camera Registry to Investigation Intelligence. Designed and presented by Team Apex for the Gujarat Statewide Surveillance Hackathon.',
    model: 'model2',
    targetTab: 'dashboard',
    targetSelector: '#demo-end-card-overlay',
    durationMs: 12000,
  },
];
